name: fooocus
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  flutter_colorpicker: ^1.0.0
  http: 1.3.0
  cached_network_image: ^3.3.1
  permission_handler: ^12.0.0+1
  flutter_cache_manager: ^3.3.1
  image_picker: ^1.1.2
  flutter_exif_rotation: ^0.5.2
  image: ^3.0.1
  path_provider: ^2.0.11
  flutter_staggered_grid_view: ^0.6.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
